import { Department, Doctor, User, Appointment, MedicalReport, NotificationItem } from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Orthopedics & Joint Replacement',
    icon_name: 'Bone',
    description: 'Specialized unit equipped with High Frequency Image Intensifier for Joint Replacement, Trauma (Fractures), Spine Surgery, Arthroscopy, and Ilizarov techniques.',
    lead_doctor: 'Dr. Tushar Patel, M.B.B.S, D. Ortho',
    total_doctors: 6,
    beds_count: 15,
    equipment_highlights: ['High Frequency Image Intensifier', '4K Arthroscopy Suite', 'Ilizarov Frame Unit', 'Digital DR X-Ray'],
    image_url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Fractures & Complex Trauma', 'Osteoarthritis', 'Spine Disorders', 'ACL/Meniscus Tears', 'Deformity Correction'],
    treatments: ['Joint Replacement Surgery', 'Trauma & Fracture Fixation', 'Arthroscopic Surgery', 'Spine Surgery', 'Ilizarov Technique']
  },
  {
    id: 'dept-2',
    name: 'Obstetrics, Gynecology & Infertility',
    icon_name: 'Baby',
    description: 'Comprehensive maternal care, high-risk pregnancy monitoring, NST, infertility treatments, and painless delivery in modern Labour Rooms.',
    lead_doctor: 'Dr. Dipti Agarwal, M.B.B.S., M.S, FICOG, FMAS',
    total_doctors: 5,
    beds_count: 10,
    equipment_highlights: ['3D 4D Voluson USG Machine', 'Non-Stress Test (NST) Unit', 'Dedicated Labour Room', 'Storz Laparoscope'],
    image_url: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['High-Risk Pregnancy', 'Infertility', 'PCOS / Ovarian Cysts', 'Uterine Fibroids', 'Gynecological Cancers'],
    treatments: ['3D/4D Voluson Fetal Scans', 'Infertility Management', 'Laparoscopic Hysterectomy', 'Painless Delivery', 'Antenatal Care']
  },
  {
    id: 'dept-3',
    name: 'Advanced Robotic Physiotherapy Clinic',
    icon_name: 'Activity',
    description: 'South Gujarat\'s innovative rehabilitation center equipped with latest Robotic & VR equipment, High Power Class-IV Laser for pain management and post-op care.',
    lead_doctor: 'Dr. Rushita Movaliya, Physiotherapist',
    total_doctors: 4,
    beds_count: 8,
    equipment_highlights: ['Robotic & VR Rehabilitation', 'High Power Class-IV Laser', 'Electrotherapy Suite', 'Spinal Traction'],
    image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Post-Op Joint Rehabilitation', 'Chronic Back & Neck Pain', 'Stroke & Neuro Recovery', 'Sports Injuries', 'Scoliosis'],
    treatments: ['Robotic Physical Therapy', 'Class-IV Laser Therapy', 'VR Balance Training', 'Post-Surgical Rehab', 'Myofascial Release']
  },
  {
    id: 'dept-4',
    name: 'General & Laparoscopic Surgery',
    icon_name: 'Stethoscope',
    description: 'Minimally invasive laparoscopic procedures, hernia repairs, gallbladder surgeries using the latest Storz Laparoscope Unit and high-end OT.',
    lead_doctor: 'Dr. Naval Singh Rajput, Family Physician & Administrator',
    total_doctors: 6,
    beds_count: 12,
    equipment_highlights: ['Latest Storz Laparoscope Unit', 'Surgical ICU', 'Modular Operation Theatre', 'C-Arm Guidance'],
    image_url: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Gallstones', 'Appendicitis', 'Abdominal Hernia', 'Piles & Fissure', 'Thyroid Lesions'],
    treatments: ['Laparoscopic Cholecystectomy', 'Appendectomy', 'Hernioplasty', 'Laser Proctology', 'General Surgery']
  },
  {
    id: 'dept-5',
    name: 'Radiology & 3D/4D Sonography',
    icon_name: 'Brain',
    description: 'Round-the-clock diagnostic imaging featuring 24*7 Digital DR X-Ray System, 3D 4D Voluson USG Machine, and pathology integration.',
    lead_doctor: 'Radiology Team',
    total_doctors: 4,
    beds_count: 5,
    equipment_highlights: ['Digital DR X-Ray System', '3D 4D Voluson Ultrasound', 'Automated Pathology Analyzer', 'NST Monitor'],
    image_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Abdominal & Pelvic Pain', 'Fetal Anomaly Detection', 'Bone Fractures', 'Chest Infections', 'Pathological Screening'],
    treatments: ['3D/4D Fetal Ultrasound', 'Digital X-Ray DR Scans', 'Full Body Blood Pathology', 'Anomaly Scans']
  },
  {
    id: 'dept-6',
    name: '24x7 Emergency & Surgical ICU',
    icon_name: 'HeartPulse',
    description: '24-hour medical emergency care, trauma management, fully equipped Surgical ICU, 24*7 Pharmacy, and Cashless Mediclaim support.',
    lead_doctor: 'Dr. Naval Singh Rajput & Emergency Team',
    total_doctors: 8,
    beds_count: 10,
    equipment_highlights: ['Surgical ICU Monitors', 'High Frequency Image Intensifier', 'Hi-Power Generator Backup', '24*7 Ambulance'],
    image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Accident & Trauma', 'Acute Abdomen', 'Respiratory Distress', 'Cardiovascular Emergencies', 'High Fever'],
    treatments: ['Trauma Stabilization', 'ICU Critical Monitoring', 'Emergency Surgery', 'Cashless Mediclaim Processing']
  }
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Tushar Patel',
    department: 'Orthopedics & Joint Replacement',
    specialization: 'Orthopaedic Consultant',
    qualification: '(M.B.B.S, D. Ortho)',
    experience_years: 15,
    consultation_fee: 500,
    rating: 4.95,
    reviews_count: 420,
    photo_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    bio: 'Renowned Orthopaedic Consultant specializing in Joint Replacement, Trauma (Fractures), Spine Surgery, Arthroscopy, and Ilizarov procedures with High Frequency Image Intensifier guidance.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: 'Mon - Sat (09:00 AM - 08:30 PM • After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.tushar.patel@skmh.org',
    is_active: true,
    availability_status: 'Available',
    education: ['D. Ortho - Recognized University', 'MBBS - Medical College'],
    achievements: ['Expert in complex Ilizarov & Trauma surgeries', 'Pioneer in advanced Joint Replacement in South Gujarat']
  },
  {
    id: 'doc-2',
    name: 'Dr. Dipti Agarwal',
    department: 'Obstetrics, Gynecology & Infertility',
    specialization: 'Obstetrician, Gynecologist & Infertility Specialist',
    qualification: '(M.B.B.S., M.S, FICOG, FMAS)',
    experience_years: 14,
    consultation_fee: 500,
    rating: 4.98,
    reviews_count: 510,
    photo_url: 'https://images.unsplash.com/photo-1594824813566-78a9010ef50a?auto=format&fit=crop&q=80&w=400',
    bio: 'Senior Obstetrician, Gynecologist & Infertility Specialist expert in high-risk pregnancy management, 3D/4D Voluson USG anomaly scanning, NST monitoring, and laparoscopic surgeries.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: 'Mon - Sat (09:00 AM - 08:30 PM • After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.dipti.agarwal@skmh.org',
    is_active: true,
    availability_status: 'In OPD',
    education: ['MS Obstetrics & Gynecology', 'FMAS Minimal Access Surgery', 'FICOG Fellow', 'MBBS'],
    achievements: ['Over 3,000 successful safe deliveries', 'Fellow in Minimal Access Surgery & Infertility Care']
  },
  {
    id: 'doc-3',
    name: 'Dr. Naval Singh Rajput',
    department: 'General & Laparoscopic Surgery',
    specialization: 'Family Physician & Clinical Administrator',
    qualification: '(M.B.B.S)',
    experience_years: 16,
    consultation_fee: 400,
    rating: 4.90,
    reviews_count: 380,
    photo_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    bio: 'Dedicated Family Physician and Clinical Administrator overseeing 24x7 emergency clinical services, outpatient consultation, and general hospital administration.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: 'Mon - Sat (09:00 AM - 08:30 PM • After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.naval.rajput@skmh.org',
    is_active: true,
    availability_status: 'In OT / Surgery',
    education: ['MBBS - General Medicine', 'Postgraduate Diploma in Health & Hospital Administration'],
    achievements: ['15+ years of clinical leadership in Silvassa', 'Distinguished Clinical Administrator']
  },
  {
    id: 'doc-4',
    name: 'Dr. Rushita Movaliya',
    department: 'Advanced Robotic Physiotherapy Clinic',
    specialization: 'Physiotherapist',
    qualification: '(B.P.T, M.P.T)',
    experience_years: 8,
    consultation_fee: 400,
    rating: 4.92,
    reviews_count: 290,
    photo_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    bio: 'Leading Physiotherapist operating South Gujarat\'s premier clinic equipped with Robotic & VR equipment and High Power Class-IV Laser for superior pre & post-operative care and pain management.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: '09:00 AM - 08:30 PM (After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.rushita.movaliya@skmh.org',
    is_active: true,
    is_on_call: false,
    consultant_type: 'Resident Consultant',
    availability_status: 'Available',
    education: ['MPT Orthopedics & Rehabilitation', 'BPT Bachelor of Physiotherapy'],
    achievements: ['Specialist in Robotic & VR Neuromuscular Therapy', 'Certified Class-IV Laser Pain Management Practitioner']
  },
  {
    id: 'doc-5',
    name: 'Dr. Jayesh Mehta',
    department: 'Emergency & Intensive Care',
    specialization: 'Visiting Interventional Cardiologist (On-Call)',
    qualification: '(M.B.B.S, M.D. Medicine, D.N.B. Cardiology)',
    experience_years: 18,
    consultation_fee: 700,
    rating: 4.96,
    reviews_count: 310,
    photo_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    bio: 'Senior Interventional Cardiologist available on emergency call for complex cardiac cases, angioplasty, pacemaker implantations, and acute coronary syndrome management.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    time_slots: ['Emergency Call', '02:00 PM', '06:00 PM'],
    opd_timings: '24x7 Emergency On-Call & Prior Appointment',
    phone: '+91 90990 57219',
    email: 'dr.jayesh.mehta@skmh.org',
    is_active: true,
    is_on_call: true,
    consultant_type: 'Visiting / On-Call',
    availability_status: 'Available',
    education: ['DNB Cardiology - National Board', 'MD Medicine', 'MBBS'],
    achievements: ['Over 2,500 successful cardiac interventions', 'Visiting Specialist for Emergency Cardiac ICU Care']
  },
  {
    id: 'doc-6',
    name: 'Dr. Sneha Shah',
    department: 'Pediatric & NICU Care',
    specialization: 'Visiting Pediatrician & Neonatologist (On-Call)',
    qualification: '(M.B.B.S, M.D. Pediatrics, Fellowship Neonatology)',
    experience_years: 12,
    consultation_fee: 600,
    rating: 4.94,
    reviews_count: 275,
    photo_url: 'https://images.unsplash.com/photo-1594824813566-78a9010ef50a?auto=format&fit=crop&q=80&w=400',
    bio: 'Expert Pediatrician & Neonatologist on-call for high-risk neonatal care, premature infant resuscitation, emergency pediatric ICU, and developmental pediatric consultations.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    time_slots: ['Emergency Call', '11:00 AM', '04:00 PM'],
    opd_timings: '24x7 Emergency On-Call & Prior Appointment',
    phone: '+91 90990 57219',
    email: 'dr.sneha.shah@skmh.org',
    is_active: true,
    is_on_call: true,
    consultant_type: 'Visiting / On-Call',
    availability_status: 'Off Duty',
    education: ['Fellowship in Neonatology', 'MD Pediatrics', 'MBBS'],
    achievements: ['Gold Medalist in Pediatric Medicine', 'Pioneer in advanced NICU emergency management']
  },
  {
    id: 'doc-7',
    name: 'Dr. Nilesh Vasavada',
    department: 'General & Laparoscopic Surgery',
    specialization: 'Visiting Neurosurgeon & Spine Specialist (On-Call)',
    qualification: '(M.B.B.S, M.S. General Surgery, M.Ch NeuroSurgery)',
    experience_years: 20,
    consultation_fee: 800,
    rating: 4.99,
    reviews_count: 440,
    photo_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    bio: 'Renowned Neurosurgeon & Spine Surgeon available on priority call for head trauma, emergency spine decompression, stroke care, and complex neurosurgical interventions.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    time_slots: ['Emergency Call', '03:00 PM', '07:00 PM'],
    opd_timings: '24x7 Emergency On-Call & Prior Appointment',
    phone: '+91 90990 57219',
    email: 'dr.nilesh.vasavada@skmh.org',
    is_active: true,
    is_on_call: true,
    consultant_type: 'Visiting / On-Call',
    education: ['M.Ch NeuroSurgery - Apex Medical Institute', 'MS General Surgery', 'MBBS'],
    achievements: ['Pioneer in Minimally Invasive Spine Surgery', 'Recognized Specialist for Emergency Neuro-Trauma Care']
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-patient-1',
    patient_code: 'SKMH-2026-PAT-101',
    email: 'patient@skmh.org',
    full_name: 'Amitabh Sharma',
    role: 'patient',
    phone: '+91 98112 23344',
    gender: 'Male',
    age: 42,
    blood_group: 'B+',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    created_at: '2026-01-15T10:00:00Z',
    allergies: ['Penicillin', 'Dust Mites'],
    chronic_conditions: ['Stage 1 Hypertension', 'Mild Osteoarthritis'],
    emergency_contact: '+91 98112 99887 (Sunita Sharma - Wife)',
    address: 'Flat 402, Royal Residency, Near Kilvani Naka, Silvassa 396230',
    medical_history_notes: 'Underwent right knee diagnostic evaluation in 2025. Regular cardiac OPD checks with Dr. Tushar Patel & Dr. Rajesh Krishna.'
  },
  {
    id: 'usr-patient-2',
    patient_code: 'SKMH-2026-PAT-102',
    email: 'priya.patel@gmail.com',
    full_name: 'Priya Patel',
    role: 'patient',
    phone: '+91 98251 44332',
    gender: 'Female',
    age: 31,
    blood_group: 'O+',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    created_at: '2026-02-10T11:20:00Z',
    allergies: ['Sulfa Drugs'],
    chronic_conditions: ['PCOS / Thyroid Screen Normal'],
    emergency_contact: '+91 98251 99110 (Rahul Patel - Husband)',
    address: 'B-12, Green Park Society, Naroli Road, Silvassa 396230',
    medical_history_notes: 'Antenatal wellness visits with Dr. Dipti Agarwal. 3D Voluson USG scan recorded clear fetal progression.'
  },
  {
    id: 'usr-patient-3',
    patient_code: 'SKMH-2026-PAT-103',
    email: 'ramesh.verma@yahoo.com',
    full_name: 'Rameshchandra Verma',
    role: 'patient',
    phone: '+91 97230 11998',
    gender: 'Male',
    age: 58,
    blood_group: 'A+',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    created_at: '2026-03-01T09:15:00Z',
    allergies: ['None Reported'],
    chronic_conditions: ['Type 2 Diabetes Mellitus', 'Lumbar Spondylosis'],
    emergency_contact: '+91 97230 88221 (Anil Verma - Son)',
    address: 'Plot 88, GIDC Industrial Estate, Amli, Silvassa 396230',
    medical_history_notes: 'Undergoing Advanced Robotic Physiotherapy under Dr. Rushita Movaliya for chronic back pain.'
  },
  {
    id: 'usr-doctor-1',
    email: 'rajesh.krishna@skmh.org',
    full_name: 'Dr. Rajesh Krishna',
    role: 'doctor',
    phone: '+91 98765 11001',
    gender: 'Male',
    age: 48,
    blood_group: 'O+',
    avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    created_at: '2025-11-01T08:00:00Z'
  },
  {
    id: 'usr-admin-1',
    email: 'admin@skmh.org',
    full_name: 'Suresh Patel (Admin)',
    role: 'admin',
    phone: '+91 99001 88776',
    gender: 'Male',
    age: 50,
    blood_group: 'A+',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    created_at: '2025-10-10T09:00:00Z'
  },
  {
    id: 'usr-superadmin-1',
    email: 'superadmin@skmh.org',
    full_name: 'Director Desk (Super Admin)',
    role: 'super_admin',
    phone: '+91 99000 11111',
    gender: 'Female',
    age: 55,
    blood_group: 'AB+',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    created_at: '2025-09-01T08:00:00Z'
  },
  {
    id: 'usr-receptionist-1',
    email: 'reception.opd@skmh.org',
    password: 'Reception@2026',
    full_name: 'Pooja Mehta (Reception Desk)',
    role: 'receptionist',
    phone: '+91 98765 11001',
    gender: 'Female',
    age: 28,
    blood_group: 'O+',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    created_at: '2026-01-01T08:00:00Z'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    user_id: 'usr-patient-1',
    patient_code: 'SKMH-2026-PAT-101',
    user_name: 'Amitabh Sharma',
    user_phone: '+91 98112 23344',
    user_email: 'patient@skmh.org',
    doctor_id: 'doc-1',
    doctor_name: 'Dr. Tushar Patel',
    department: 'Orthopedics & Joint Replacement',
    appointment_date: '2026-08-01',
    time_slot: '10:30 AM',
    status: 'completed',
    reason: 'Severe right knee pain while walking & climbing stairs.',
    notes: 'Patient advised non-weight bearing exercise and knee sleeve support.',
    created_at: '2026-08-01T14:20:00Z',
    vitals: {
      blood_pressure: '130/85 mmHg',
      pulse_rate: '74 bpm',
      temperature: '98.4 °F',
      spo2: '99%',
      weight_kg: '78'
    },
    diagnosis: 'Primary Osteoarthritis Right Knee (Grade II) with Medial Joint Space Narrowing',
    prescribed_medicines: [
      {
        id: 'med-1',
        name: 'Tab. Glucosamine + Chondroitin (500mg)',
        dosage: '1 Tablet',
        frequency: '1-0-1 (Twice Daily)',
        duration: '1 Month',
        instructions: 'Take after principal meals'
      },
      {
        id: 'med-2',
        name: 'Tab. Aceclofenac + Paracetamol (100mg/325mg)',
        dosage: '1 Tablet',
        frequency: '1-0-1 (As Needed)',
        duration: '5 Days',
        instructions: 'After meals for acute pain'
      },
      {
        id: 'med-3',
        name: 'Cap. Omeprazole (20mg)',
        dosage: '1 Capsule',
        frequency: '1-0-0 (Once Daily)',
        duration: '10 Days',
        instructions: '30 mins before breakfast'
      }
    ],
    recommended_tests: [
      'Digital X-Ray Right Knee Joint (AP & Lateral Weight-Bearing)',
      'Serum Calcium & Vitamin D3 (25-OH)',
      'Uric Acid Level'
    ],
    higher_reference: {
      referred_to_hospital: 'Civil Hospital Surat / Spine & Joint Tertiary Institute',
      specialist_center: 'Advanced Arthroscopy & Knee Reconstruction Center',
      referral_reason: 'Optional higher tertiary consult if conservative therapy fails to relieve nocturnal joint pain after 4 weeks.',
      urgency: 'Routine',
      reference_date: '2026-08-01',
      doctor_signature_notes: 'Dr. Tushar Patel (M.B.B.S, D. Ortho) - Senior Orthopedic Specialist'
    },
    follow_up_date: '2026-08-25'
  },
  {
    id: 'apt-102',
    user_id: 'usr-patient-1',
    patient_code: 'SKMH-2026-PAT-101',
    user_name: 'Amitabh Sharma',
    user_phone: '+91 98112 23344',
    user_email: 'patient@skmh.org',
    doctor_id: 'doc-3',
    doctor_name: 'Dr. Naval Singh Rajput',
    department: 'General & Laparoscopic Surgery',
    appointment_date: '2026-08-18',
    time_slot: '02:00 PM',
    status: 'pending',
    reason: 'Mild right upper quadrant discomfort & epigastric fullness.',
    notes: 'Awaiting abdominal sonography ultrasound report.',
    created_at: '2026-08-05T09:15:00Z'
  },
  {
    id: 'apt-103',
    user_id: 'usr-patient-2',
    patient_code: 'SKMH-2026-PAT-102',
    user_name: 'Priya Patel',
    user_phone: '+91 98251 44332',
    user_email: 'priya.patel@gmail.com',
    doctor_id: 'doc-2',
    doctor_name: 'Dr. Dipti Agarwal',
    department: 'Obstetrics, Gynecology & Infertility',
    appointment_date: '2026-07-20',
    time_slot: '11:00 AM',
    status: 'completed',
    reason: 'Second trimester routine antenatal check & fetal anomaly scan review.',
    notes: 'Fetal growth metrics aligned with gestational age.',
    created_at: '2026-07-15T11:00:00Z',
    vitals: {
      blood_pressure: '118/76 mmHg',
      pulse_rate: '78 bpm',
      temperature: '98.6 °F',
      spo2: '99%',
      weight_kg: '62'
    },
    diagnosis: '22 Weeks Gestation - Single Live Intrauterine Pregnancy (Normal Anomaly Scan)',
    prescribed_medicines: [
      {
        id: 'med-4',
        name: 'Tab. Ferrous Ascorbate + Folic Acid',
        dosage: '1 Tablet',
        frequency: '0-1-0 (Once Daily)',
        duration: '3 Months',
        instructions: 'Take with lemon water or post lunch'
      },
      {
        id: 'med-5',
        name: 'Tab. Calcium Citrate + Vitamin D3 (500mg)',
        dosage: '1 Tablet',
        frequency: '1-0-1 (Twice Daily)',
        duration: '3 Months',
        instructions: 'After breakfast & dinner'
      }
    ],
    recommended_tests: [
      'Fetal Growth & Doppler Ultrasonography (3D Voluson)',
      'Complete Hemogram (Hb % check)',
      'Oral Glucose Tolerance Test (OGTT 75g)'
    ],
    follow_up_date: '2026-08-20'
  },
  {
    id: 'apt-104',
    user_id: 'usr-patient-3',
    patient_code: 'SKMH-2026-PAT-103',
    user_name: 'Rameshchandra Verma',
    user_phone: '+91 97230 11998',
    user_email: 'ramesh.verma@yahoo.com',
    doctor_id: 'doc-4',
    doctor_name: 'Dr. Rushita Movaliya',
    department: 'Advanced Robotic Physiotherapy Clinic',
    appointment_date: '2026-08-04',
    time_slot: '04:00 PM',
    status: 'completed',
    reason: 'Chronic lower back ache radiating to left thigh with morning stiffness.',
    notes: 'Undergoing Class-IV Laser therapy & VR spinal traction.',
    created_at: '2026-08-01T10:00:00Z',
    vitals: {
      blood_pressure: '138/88 mmHg',
      pulse_rate: '80 bpm',
      temperature: '98.2 °F',
      spo2: '98%',
      weight_kg: '82'
    },
    diagnosis: 'L4-L5 Lumbar Spondylosis with Mild Left Sciatic Nerve Impingement',
    prescribed_medicines: [
      {
        id: 'med-6',
        name: 'Cap. Pregabalin (75mg) + Methylcobalamin (1500mcg)',
        dosage: '1 Capsule',
        frequency: '0-0-1 (Nightly)',
        duration: '15 Days',
        instructions: 'Take at bedtime'
      },
      {
        id: 'med-7',
        name: 'Topical Diclofenac + Menthol Gel',
        dosage: 'Local Application',
        frequency: '1-0-1 (Twice Daily)',
        duration: '10 Days',
        instructions: 'Gently apply over lumbar spine, no heavy massage'
      }
    ],
    recommended_tests: [
      'Lumbar Spine MRI (1.5 Tesla Scan)',
      'HbA1c Glycated Hemoglobin',
      'Class-IV High Power Laser Therapy Sessions (10 sittings)'
    ],
    higher_reference: {
      referred_to_hospital: 'Apex Neuro-Spine Super Specialty Hospital, Surat',
      specialist_center: 'Department of Spine Surgery & Interventional Pain Medicine',
      referral_reason: 'Higher tertiary neuro-spine evaluation for selective nerve root block if numbness in left foot persists.',
      urgency: 'Urgent',
      reference_date: '2026-08-04',
      doctor_signature_notes: 'Dr. Rushita Movaliya (M.P.T) - Senior Robotic Physiotherapy Specialist'
    },
    follow_up_date: '2026-08-18'
  }
];

export const INITIAL_REPORTS: MedicalReport[] = [
  {
    id: 'rep-1',
    user_id: 'usr-patient-1',
    user_name: 'Amitabh Sharma',
    title: 'Comprehensive Lipid Profile & Blood Sugar',
    category: 'Blood Test',
    file_name: 'Lipid_Profile_Sharma_Aug2026.pdf',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: '1.2 MB',
    uploaded_at: '2026-08-02T10:30:00Z',
    doctor_notes: 'Triglycerides slightly elevated (185 mg/dL). Recommended low-carb diet and 30 mins brisk walking.',
    uploaded_by_role: 'doctor'
  },
  {
    id: 'rep-2',
    user_id: 'usr-patient-1',
    user_name: 'Amitabh Sharma',
    title: '2D Echo & ECG Cardiac Report',
    category: 'Lab Result',
    file_name: '2D_Echo_ECG_Aug2026.pdf',
    file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    file_size: '2.8 MB',
    uploaded_at: '2026-08-03T16:10:00Z',
    doctor_notes: 'Ejection fraction 62%. Normal valvular movement. No signs of ischemia.',
    uploaded_by_role: 'doctor'
  },
  {
    id: 'rep-3',
    user_id: 'usr-patient-1',
    user_name: 'Amitabh Sharma',
    title: 'Right Knee Joint X-Ray (AP & Lateral View)',
    category: 'Radiology / X-Ray',
    file_name: 'Knee_XRay_Amitabh.png',
    file_url: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&q=80&w=800',
    file_size: '3.5 MB',
    uploaded_at: '2026-08-05T08:45:00Z',
    doctor_notes: 'Uploaded by patient prior to consultation with Dr. Vikram Roy.',
    uploaded_by_role: 'patient'
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-patient-1',
    title: 'Appointment Confirmed! 🏥',
    message: 'Your appointment with Dr. Rajesh Krishna on Aug 12, 2026 at 10:30 AM is confirmed.',
    type: 'appointment',
    read: false,
    created_at: '2026-08-01T14:21:00Z'
  },
  {
    id: 'notif-2',
    user_id: 'usr-patient-1',
    title: 'New Medical Report Uploaded 📄',
    message: 'Dr. Rajesh Krishna uploaded your "Comprehensive Lipid Profile & Blood Sugar" test result.',
    type: 'report',
    read: true,
    created_at: '2026-08-02T10:31:00Z'
  }
];
