import { Department, Doctor, User, Appointment, MedicalReport, NotificationItem } from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Orthopedics & Joint Replacement',
    icon_name: 'Bone',
    description: 'Specialized unit equipped with High Frequency Image Intensifier for Joint Replacement, Trauma (Fractures), Spine Surgery, Arthroscopy, and Ilizarov techniques.',
    lead_doctor: 'Dr. Tushar Patel, M.B.B.S, D. Ortho',
    total_doctors: 6,
    beds_count: 15,
    equipment_highlights: ['High Frequency Image Intensifier', '4K Arthroscopy Suite', 'Ilizarov Frame Unit', 'Digital DR X-Ray'],
    image_url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Fractures & Complex Trauma', 'Osteoarthritis', 'Spine Disorders', 'ACL/Meniscus Tears', 'Deformity Correction'],
    treatments: ['Joint Replacement Surgery', 'Trauma & Fracture Fixation', 'Arthroscopic Surgery', 'Spine Surgery', 'Ilizarov Technique']
  },
  {
    id: 'dept-2',
    name: 'Obstetrics, Gynecology & Infertility',
    icon_name: 'Baby',
    description: 'Comprehensive maternal care, high-risk pregnancy monitoring, NST, infertility treatments, and painless delivery in modern Labour Rooms.',
    lead_doctor: 'Dr. Dipti Agarwal, M.B.B.S., M.S, FICOG, FMAS',
    total_doctors: 5,
    beds_count: 10,
    equipment_highlights: ['3D 4D Voluson USG Machine', 'Non-Stress Test (NST) Unit', 'Dedicated Labour Room', 'Storz Laparoscope'],
    image_url: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['High-Risk Pregnancy', 'Infertility', 'PCOS / Ovarian Cysts', 'Uterine Fibroids', 'Gynecological Cancers'],
    treatments: ['3D/4D Voluson Fetal Scans', 'Infertility Management', 'Laparoscopic Hysterectomy', 'Painless Delivery', 'Antenatal Care']
  },
  {
    id: 'dept-3',
    name: 'Advanced Robotic Physiotherapy Clinic',
    icon_name: 'Activity',
    description: 'South Gujarat\'s innovative rehabilitation center equipped with latest Robotic & VR equipment, High Power Class-IV Laser for pain management and post-op care.',
    lead_doctor: 'Dr. Rushita Movaliya, Physiotherapist',
    total_doctors: 4,
    beds_count: 8,
    equipment_highlights: ['Robotic & VR Rehabilitation', 'High Power Class-IV Laser', 'Electrotherapy Suite', 'Spinal Traction'],
    image_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Post-Op Joint Rehabilitation', 'Chronic Back & Neck Pain', 'Stroke & Neuro Recovery', 'Sports Injuries', 'Scoliosis'],
    treatments: ['Robotic Physical Therapy', 'Class-IV Laser Therapy', 'VR Balance Training', 'Post-Surgical Rehab', 'Myofascial Release']
  },
  {
    id: 'dept-4',
    name: 'General & Laparoscopic Surgery',
    icon_name: 'Stethoscope',
    description: 'Minimally invasive laparoscopic procedures, hernia repairs, gallbladder surgeries using the latest Storz Laparoscope Unit and high-end OT.',
    lead_doctor: 'Dr. Naval Singh Rajput, Family Physician & Administrator',
    total_doctors: 6,
    beds_count: 12,
    equipment_highlights: ['Latest Storz Laparoscope Unit', 'Surgical ICU', 'Modular Operation Theatre', 'C-Arm Guidance'],
    image_url: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Gallstones', 'Appendicitis', 'Abdominal Hernia', 'Piles & Fissure', 'Thyroid Lesions'],
    treatments: ['Laparoscopic Cholecystectomy', 'Appendectomy', 'Hernioplasty', 'Laser Proctology', 'General Surgery']
  },
  {
    id: 'dept-5',
    name: 'Radiology & 3D/4D Sonography',
    icon_name: 'Brain',
    description: 'Round-the-clock diagnostic imaging featuring 24*7 Digital DR X-Ray System, 3D 4D Voluson USG Machine, and pathology integration.',
    lead_doctor: 'Radiology Team',
    total_doctors: 4,
    beds_count: 5,
    equipment_highlights: ['Digital DR X-Ray System', '3D 4D Voluson Ultrasound', 'Automated Pathology Analyzer', 'NST Monitor'],
    image_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Abdominal & Pelvic Pain', 'Fetal Anomaly Detection', 'Bone Fractures', 'Chest Infections', 'Pathological Screening'],
    treatments: ['3D/4D Fetal Ultrasound', 'Digital X-Ray DR Scans', 'Full Body Blood Pathology', 'Anomaly Scans']
  },
  {
    id: 'dept-6',
    name: '24x7 Emergency & Surgical ICU',
    icon_name: 'HeartPulse',
    description: '24-hour medical emergency care, trauma management, fully equipped Surgical ICU, 24*7 Pharmacy, and Cashless Mediclaim support.',
    lead_doctor: 'Dr. Naval Singh Rajput & Emergency Team',
    total_doctors: 8,
    beds_count: 10,
    equipment_highlights: ['Surgical ICU Monitors', 'High Frequency Image Intensifier', 'Hi-Power Generator Backup', '24*7 Ambulance'],
    image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    common_conditions: ['Accident & Trauma', 'Acute Abdomen', 'Respiratory Distress', 'Cardiovascular Emergencies', 'High Fever'],
    treatments: ['Trauma Stabilization', 'ICU Critical Monitoring', 'Emergency Surgery', 'Cashless Mediclaim Processing']
  }
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Tushar Patel',
    department: 'Orthopedics & Joint Replacement',
    specialization: 'Orthopaedic Consultant',
    qualification: '(M.B.B.S, D. Ortho)',
    experience_years: 15,
    consultation_fee: 500,
    rating: 4.95,
    reviews_count: 420,
    photo_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    bio: 'Renowned Orthopaedic Consultant specializing in Joint Replacement, Trauma (Fractures), Spine Surgery, Arthroscopy, and Ilizarov procedures with High Frequency Image Intensifier guidance.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: 'Mon - Sat (09:00 AM - 08:30 PM • After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.tushar.patel@skmh.org',
    is_active: true,
    availability_status: 'Available',
    signature_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=300',
    stamp_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=300',
    registration_number: 'GMC-SILVASSA-REG-2008-5412',
    designation: 'Senior Orthopedic Surgeon & HOD',
    is_authorised_signatory: true,
    education: ['D. Ortho - Recognized University', 'MBBS - Medical College'],
    achievements: ['Expert in complex Ilizarov & Trauma surgeries', 'Pioneer in advanced Joint Replacement in South Gujarat']
  },
  {
    id: 'doc-2',
    name: 'Dr. Dipti Agarwal',
    department: 'Obstetrics, Gynecology & Infertility',
    specialization: 'Obstetrician, Gynecologist & Infertility Specialist',
    qualification: '(M.B.B.S., M.S, FICOG, FMAS)',
    experience_years: 14,
    consultation_fee: 500,
    rating: 4.98,
    reviews_count: 510,
    photo_url: 'https://images.unsplash.com/photo-1594824813566-78a9010ef50a?auto=format&fit=crop&q=80&w=400',
    bio: 'Senior Obstetrician, Gynecologist & Infertility Specialist expert in high-risk pregnancy management, 3D/4D Voluson USG anomaly scanning, NST monitoring, and laparoscopic surgeries.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: 'Mon - Sat (09:00 AM - 08:30 PM • After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.dipti.agarwal@skmh.org',
    is_active: true,
    availability_status: 'In OPD',
    signature_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=300',
    stamp_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=300',
    registration_number: 'GMC-SILVASSA-REG-2012-9918',
    designation: 'Senior Gynecologist & Laparoscopic Surgeon',
    is_authorised_signatory: true,
    education: ['MS Obstetrics & Gynecology', 'FMAS Minimal Access Surgery', 'FICOG Fellow', 'MBBS'],
    achievements: ['Over 3,000 successful safe deliveries', 'Fellow in Minimal Access Surgery & Infertility Care']
  },
  {
    id: 'doc-3',
    name: 'Dr. Naval Singh Rajput',
    department: 'General & Laparoscopic Surgery',
    specialization: 'Family Physician & Clinical Administrator',
    qualification: '(M.B.B.S)',
    experience_years: 16,
    consultation_fee: 400,
    rating: 4.90,
    reviews_count: 380,
    photo_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    bio: 'Dedicated Family Physician and Clinical Administrator overseeing 24x7 emergency clinical services, outpatient consultation, and general hospital administration.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: 'Mon - Sat (09:00 AM - 08:30 PM • After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.naval.rajput@skmh.org',
    is_active: true,
    availability_status: 'In OT / Surgery',
    signature_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=300',
    stamp_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=300',
    registration_number: 'GMC-SILVASSA-REG-2010-3321',
    designation: 'Clinical Administrator & Family Physician',
    is_authorised_signatory: true,
    education: ['MBBS - General Medicine', 'Postgraduate Diploma in Health & Hospital Administration'],
    achievements: ['15+ years of clinical leadership in Silvassa', 'Distinguished Clinical Administrator']
  },
  {
    id: 'doc-4',
    name: 'Dr. Rushita Movaliya',
    department: 'Advanced Robotic Physiotherapy Clinic',
    specialization: 'Physiotherapist',
    qualification: '(B.P.T, M.P.T)',
    experience_years: 8,
    consultation_fee: 400,
    rating: 4.92,
    reviews_count: 290,
    photo_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400',
    bio: 'Leading Physiotherapist operating South Gujarat\'s premier clinic equipped with Robotic & VR equipment and High Power Class-IV Laser for superior pre & post-operative care and pain management.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    time_slots: ['09:00 AM', '11:00 AM', '01:00 PM', '06:00 PM', '08:00 PM'],
    opd_timings: '09:00 AM - 08:30 PM (After 8:30 PM Emergency Only)',
    phone: '+91 90990 57219',
    email: 'dr.rushita.movaliya@skmh.org',
    is_active: true,
    is_on_call: false,
    consultant_type: 'Resident Consultant',
    availability_status: 'Available',
    signature_url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=300',
    stamp_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=300',
    registration_number: 'GMC-SILVASSA-REG-2018-4491',
    designation: 'Chief Robotic Physiotherapy Specialist',
    is_authorised_signatory: true,
    education: ['MPT Orthopedics & Rehabilitation', 'BPT Bachelor of Physiotherapy'],
    achievements: ['Specialist in Robotic & VR Neuromuscular Therapy', 'Certified Class-IV Laser Pain Management Practitioner']
  },
  {
    id: 'doc-5',
    name: 'Dr. Jayesh Mehta',
    department: 'Emergency & Intensive Care',
    specialization: 'Visiting Interventional Cardiologist (On-Call)',
    qualification: '(M.B.B.S, M.D. Medicine, D.N.B. Cardiology)',
    experience_years: 18,
    consultation_fee: 700,
    rating: 4.96,
    reviews_count: 310,
    photo_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400',
    bio: 'Senior Interventional Cardiologist available on emergency call for complex cardiac cases, angioplasty, pacemaker implantations, and acute coronary syndrome management.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    time_slots: ['Emergency Call', '02:00 PM', '06:00 PM'],
    opd_timings: '24x7 Emergency On-Call & Prior Appointment',
    phone: '+91 90990 57219',
    email: 'dr.jayesh.mehta@skmh.org',
    is_active: true,
    is_on_call: true,
    consultant_type: 'Visiting / On-Call',
    availability_status: 'Available',
    education: ['DNB Cardiology - National Board', 'MD Medicine', 'MBBS'],
    achievements: ['Over 2,500 successful cardiac interventions', 'Visiting Specialist for Emergency Cardiac ICU Care']
  },
  {
    id: 'doc-6',
    name: 'Dr. Sneha Shah',
    department: 'Pediatric & NICU Care',
    specialization: 'Visiting Pediatrician & Neonatologist (On-Call)',
    qualification: '(M.B.B.S, M.D. Pediatrics, Fellowship Neonatology)',
    experience_years: 12,
    consultation_fee: 600,
    rating: 4.94,
    reviews_count: 275,
    photo_url: 'https://images.unsplash.com/photo-1594824813566-78a9010ef50a?auto=format&fit=crop&q=80&w=400',
    bio: 'Expert Pediatrician & Neonatologist on-call for high-risk neonatal care, premature infant resuscitation, emergency pediatric ICU, and developmental pediatric consultations.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    time_slots: ['Emergency Call', '11:00 AM', '04:00 PM'],
    opd_timings: '24x7 Emergency On-Call & Prior Appointment',
    phone: '+91 90990 57219',
    email: 'dr.sneha.shah@skmh.org',
    is_active: true,
    is_on_call: true,
    consultant_type: 'Visiting / On-Call',
    availability_status: 'Off Duty',
    education: ['Fellowship in Neonatology', 'MD Pediatrics', 'MBBS'],
    achievements: ['Gold Medalist in Pediatric Medicine', 'Pioneer in advanced NICU emergency management']
  },
  {
    id: 'doc-7',
    name: 'Dr. Nilesh Vasavada',
    department: 'General & Laparoscopic Surgery',
    specialization: 'Visiting Neurosurgeon & Spine Specialist (On-Call)',
    qualification: '(M.B.B.S, M.S. General Surgery, M.Ch NeuroSurgery)',
    experience_years: 20,
    consultation_fee: 800,
    rating: 4.99,
    reviews_count: 440,
    photo_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400',
    bio: 'Renowned Neurosurgeon & Spine Surgeon available on priority call for head trauma, emergency spine decompression, stroke care, and complex neurosurgical interventions.',
    availability_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    time_slots: ['Emergency Call', '03:00 PM', '07:00 PM'],
    opd_timings: '24x7 Emergency On-Call & Prior Appointment',
    phone: '+91 90990 57219',
    email: 'dr.nilesh.vasavada@skmh.org',
    is_active: true,
    is_on_call: true,
    consultant_type: 'Visiting / On-Call',
    education: ['M.Ch NeuroSurgery - Apex Medical Institute', 'MS General Surgery', 'MBBS'],
    achievements: ['Pioneer in Minimally Invasive Spine Surgery', 'Recognized Specialist for Emergency Neuro-Trauma Care']
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-doctor-1',
    email: 'rajesh.krishna@skmh.org',
    full_name: 'Dr. Rajesh Krishna',
    role: 'doctor',
    phone: '+91 98765 11001',
    gender: 'Male',
    age: 48,
    blood_group: 'O+',
    avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=200',
    created_at: '2025-11-01T08:00:00Z'
  },
  {
    id: 'usr-admin-1',
    email: 'shreekrishna@skmh.org',
    password: 'Krishna@123',
    full_name: 'SHREEKRISHNA (Admin)',
    role: 'admin',
    phone: '+91 99001 88776',
    gender: 'Male',
    age: 50,
    blood_group: 'A+',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    created_at: '2025-10-10T09:00:00Z'
  },
  {
    id: 'usr-superadmin-1',
    email: 'SHREEKRISHNA',
    password: 'Krishna@123',
    full_name: 'SHREEKRISHNA (Super Admin)',
    role: 'super_admin',
    phone: '+91 99000 11111',
    gender: 'Male',
    age: 55,
    blood_group: 'AB+',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    created_at: '2025-09-01T08:00:00Z'
  },
  {
    id: 'usr-receptionist-1',
    email: 'reception.opd@skmh.org',
    password: 'Reception@2026',
    full_name: 'Pooja Mehta (Reception Desk)',
    role: 'receptionist',
    phone: '+91 98765 11001',
    gender: 'Female',
    age: 28,
    blood_group: 'O+',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    created_at: '2026-01-01T08:00:00Z'
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [];

export const INITIAL_REPORTS: MedicalReport[] = [];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];

export const INITIAL_BOT_FAQS = [
  {
    id: 'faq-1',
    question: 'What are the OPD consultation timings?',
    answer: 'Our OPD runs Monday through Saturday from 09:00 AM to 08:30 PM. Emergency & Trauma services operate 24 hours a day, 7 days a week.',
    keywords: ['opd', 'timing', 'time', 'hours', 'open', 'schedule'],
    category: 'OPD & Timings' as const,
    is_active: true,
    click_count: 142
  },
  {
    id: 'faq-2',
    question: 'Where is Shree Krishna Multispeciality Hospital located?',
    answer: 'We are located at: Opp. Horizon Tower, Kilvani Road, Mitu Apartment, C/o - Gulabbhai Patel, Amli, Silvassa - 396230 (UT of Dadra & Nagar Haveli). Landmark: Opposite Horizon Tower.',
    keywords: ['location', 'address', 'where', 'map', 'reach', 'silvassa', 'landmark'],
    category: 'General Info' as const,
    is_active: true,
    click_count: 98
  },
  {
    id: 'faq-3',
    question: 'Which payment modes & insurance TPAs are accepted?',
    answer: 'We accept Cash, Debit/Credit Cards, Google Pay/PhonePe UPI QR, and offer Cashless Mediclaim TPA support for all major health insurance providers (Star Health, ICICI Lombard, HDFC ERGO, SBI General, Care Health, Bajaj Allianz, etc.).',
    keywords: ['payment', 'upi', 'insurance', 'tpa', 'cashless', 'card', 'mediclaim', 'policy'],
    category: 'Billing & Insurance' as const,
    is_active: true,
    click_count: 115
  },
  {
    id: 'faq-4',
    question: 'What is the 24x7 Emergency Helpline Number?',
    answer: 'In case of trauma or medical emergency, call our 24/7 Hotline: +91 90990 57219 or Landline Desk: (0260) 264-9999. Emergency ambulance dispatch is available round the clock.',
    keywords: ['emergency', 'helpline', 'ambulance', 'phone', 'contact', 'call', 'number', 'urgent', 'trauma'],
    category: 'Emergency & Care' as const,
    is_active: true,
    click_count: 205
  },
  {
    id: 'faq-5',
    question: 'What are the room tariffs & IPD bed charges?',
    answer: 'General Ward Bed: ₹1,200/day | Semi-Private AC Room: ₹1,800/day | Deluxe AC Private Room: ₹2,500/day | Super Deluxe Suite: ₹4,500/day | Surgical ICU Bed with Monitor: ₹3,500/day.',
    keywords: ['room', 'tariff', 'bed', 'charge', 'icu', 'ward', 'deluxe', 'rate', 'cost'],
    category: 'Facilities & Admission' as const,
    is_active: true,
    click_count: 87
  },
  {
    id: 'faq-6',
    question: 'What are the patient visiting hours for wards & ICU?',
    answer: 'General Ward Visiting Hours: Morning 10:00 AM - 12:00 PM and Evening 05:00 PM - 07:00 PM. Surgical ICU Visitor Entry: Strictly 05:00 PM - 06:00 PM (1 Pass per patient family).',
    keywords: ['visit', 'visitor', 'hours', 'family', 'pass', 'icu entry', 'allowed'],
    category: 'Facilities & Admission' as const,
    is_active: true,
    click_count: 64
  }
];

